# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import converter_pb2 as converter__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in converter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConverterStub(object):
    """The Converter service offers three kinds of RPC streaming methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerStreamingConvert = channel.unary_stream(
                '/converter.Converter/ServerStreamingConvert',
                request_serializer=converter__pb2.DecimalRequest.SerializeToString,
                response_deserializer=converter__pb2.BinaryResponse.FromString,
                _registered_method=True)
        self.ClientStreamingConvert = channel.stream_unary(
                '/converter.Converter/ClientStreamingConvert',
                request_serializer=converter__pb2.DecimalRequest.SerializeToString,
                response_deserializer=converter__pb2.BinaryResponse.FromString,
                _registered_method=True)
        self.BidirectionalStreamingConvert = channel.stream_stream(
                '/converter.Converter/BidirectionalStreamingConvert',
                request_serializer=converter__pb2.DecimalRequest.SerializeToString,
                response_deserializer=converter__pb2.BinaryResponse.FromString,
                _registered_method=True)


class ConverterServicer(object):
    """The Converter service offers three kinds of RPC streaming methods.
    """

    def ServerStreamingConvert(self, request, context):
        """1. Server Streaming: Client sends one DecimalRequest and gets a stream of BinaryResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamingConvert(self, request_iterator, context):
        """2. Client Streaming: Client sends a stream of DecimalRequest and gets one BinaryResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStreamingConvert(self, request_iterator, context):
        """3. Bidirectional Streaming: Both sides send streams.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerStreamingConvert': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingConvert,
                    request_deserializer=converter__pb2.DecimalRequest.FromString,
                    response_serializer=converter__pb2.BinaryResponse.SerializeToString,
            ),
            'ClientStreamingConvert': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamingConvert,
                    request_deserializer=converter__pb2.DecimalRequest.FromString,
                    response_serializer=converter__pb2.BinaryResponse.SerializeToString,
            ),
            'BidirectionalStreamingConvert': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStreamingConvert,
                    request_deserializer=converter__pb2.DecimalRequest.FromString,
                    response_serializer=converter__pb2.BinaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'converter.Converter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('converter.Converter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Converter(object):
    """The Converter service offers three kinds of RPC streaming methods.
    """

    @staticmethod
    def ServerStreamingConvert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/converter.Converter/ServerStreamingConvert',
            converter__pb2.DecimalRequest.SerializeToString,
            converter__pb2.BinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientStreamingConvert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/converter.Converter/ClientStreamingConvert',
            converter__pb2.DecimalRequest.SerializeToString,
            converter__pb2.BinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BidirectionalStreamingConvert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/converter.Converter/BidirectionalStreamingConvert',
            converter__pb2.DecimalRequest.SerializeToString,
            converter__pb2.BinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
