# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: converter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onverter.proto\x12\tconverter\" \n\x0e\x44\x65\x63imalRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\" \n\x0e\x42inaryResponse\x12\x0e\n\x06\x62inary\x18\x01 \x01(\t2\x81\x02\n\tConverter\x12O\n\x13\x43onvertServerStream\x12\x19.converter.DecimalRequest\x1a\x19.converter.BinaryResponse\"\x00\x30\x01\x12O\n\x13\x43onvertClientStream\x12\x19.converter.DecimalRequest\x1a\x19.converter.BinaryResponse\"\x00(\x01\x12R\n\x14\x43onvertBidirectional\x12\x19.converter.DecimalRequest\x1a\x19.converter.BinaryResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIMALREQUEST']._serialized_start=30
  _globals['_DECIMALREQUEST']._serialized_end=62
  _globals['_BINARYRESPONSE']._serialized_start=64
  _globals['_BINARYRESPONSE']._serialized_end=96
  _globals['_CONVERTER']._serialized_start=99
  _globals['_CONVERTER']._serialized_end=356
# @@protoc_insertion_point(module_scope)
