# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import converter_pb2 as converter__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in converter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConverterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertServerStream = channel.unary_stream(
                '/converter.Converter/ConvertServerStream',
                request_serializer=converter__pb2.DecimalRequest.SerializeToString,
                response_deserializer=converter__pb2.BinaryResponse.FromString,
                _registered_method=True)
        self.ConvertClientStream = channel.stream_unary(
                '/converter.Converter/ConvertClientStream',
                request_serializer=converter__pb2.DecimalRequest.SerializeToString,
                response_deserializer=converter__pb2.BinaryResponse.FromString,
                _registered_method=True)
        self.ConvertBidirectional = channel.stream_stream(
                '/converter.Converter/ConvertBidirectional',
                request_serializer=converter__pb2.DecimalRequest.SerializeToString,
                response_deserializer=converter__pb2.BinaryResponse.FromString,
                _registered_method=True)


class ConverterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertServerStream(self, request, context):
        """Server streaming: client sends a single decimal; server streams back binary digits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertClientStream(self, request_iterator, context):
        """Client streaming: client sends a stream of decimals; server replies with a single response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertBidirectional(self, request_iterator, context):
        """Bidirectional streaming: both sides exchange streams.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ConvertServerStream,
                    request_deserializer=converter__pb2.DecimalRequest.FromString,
                    response_serializer=converter__pb2.BinaryResponse.SerializeToString,
            ),
            'ConvertClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ConvertClientStream,
                    request_deserializer=converter__pb2.DecimalRequest.FromString,
                    response_serializer=converter__pb2.BinaryResponse.SerializeToString,
            ),
            'ConvertBidirectional': grpc.stream_stream_rpc_method_handler(
                    servicer.ConvertBidirectional,
                    request_deserializer=converter__pb2.DecimalRequest.FromString,
                    response_serializer=converter__pb2.BinaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'converter.Converter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('converter.Converter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Converter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/converter.Converter/ConvertServerStream',
            converter__pb2.DecimalRequest.SerializeToString,
            converter__pb2.BinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/converter.Converter/ConvertClientStream',
            converter__pb2.DecimalRequest.SerializeToString,
            converter__pb2.BinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertBidirectional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/converter.Converter/ConvertBidirectional',
            converter__pb2.DecimalRequest.SerializeToString,
            converter__pb2.BinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
