# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: binary_converter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'binary_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62inary_converter.proto\x12\x0f\x62inaryconverter\"\x1f\n\rBinaryRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\" \n\x0e\x42inaryResponse\x12\x0e\n\x06\x62inary\x18\x01 \x01(\t2e\n\x0f\x42inaryConverter\x12R\n\x0f\x43onvertToBinary\x12\x1e.binaryconverter.BinaryRequest\x1a\x1f.binaryconverter.BinaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'binary_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYREQUEST']._serialized_start=43
  _globals['_BINARYREQUEST']._serialized_end=74
  _globals['_BINARYRESPONSE']._serialized_start=76
  _globals['_BINARYRESPONSE']._serialized_end=108
  _globals['_BINARYCONVERTER']._serialized_start=110
  _globals['_BINARYCONVERTER']._serialized_end=211
# @@protoc_insertion_point(module_scope)
